version: '3'
services:
  nginx:
    build:
      context: "."
      dockerfile: "./nginx/Dockerfile"
    image: raqqun0101/nginx-kanboard:latest
    depends_on:
      - php
      - db
    restart: always
    ports:
      - "80:80"
    environment:
      DATABASE_URL: mysql://kb:kb-secret@db/kanboard
  php:
    build:
      context: "."
      dockerfile: "./php-fpm/Dockerfile"
    image: raqqun0101/php-fpm-kanboard:latest
    depends_on:
      - db
    restart: always
  db:
    image: mariadb:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kanboard
      MYSQL_USER: kb
      MYSQL_PASSWORD: kb-secret
